# Generated by Django 5.1.6 on 2025-03-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='UserMessages_id',
        ),
        migrations.RemoveField(
            model_name='usermessages',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserMessages',
        ),
    ]
