# Generated by Django 5.1.6 on 2025-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_remove_message_usermessages_id_message_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time_create']},
        ),
    ]
