# Generated by Django 5.1.6 on 2025-03-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time_create']},
        ),
    ]
