# Generated by Django 5.1.6 on 2025-03-02 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='UserMessages_id',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='messanger.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='None', max_length=70),
        ),
        migrations.AlterField(
            model_name='message',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messanger.chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserMessages',
        ),
    ]
