# Generated by Django 5.1.6 on 2025-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
