# Generated by Django 5.2.1 on 2025-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0006_userchat_is_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
